### ISSUE TITLE
Database Tables

### ISSUE THREAD

**Issue by andrewdmaclean** [JoshBeveridge/app_punch#2]
Good Afternoon @joshdrink,

Looking to test out the app for use in our Teen Dev Bootcamp program here in Victoria (always great to meet a fellow Canuck) but not sure where to start with the DB in terms of tables. I have successfully created and connected to the mySQL DB but assistance as to how to get the rest setup would be really appreciated!

Any help would be appreciated!

Cheers,
Andrew

**Comment by JoshBeveridge** [comment]
Hey @theportablegeek I'm so sorry I missed this request way back in the day. I wasn't in the habit of properly keeping track of my Github repos. I haven't touched this repo in a very long time, but if you still need insight, by all means, you have my attention now. Again, my apologies!

**Comment by andrewdmaclean** [comment]
No worries @joshdrink just cleaning up my GitHub and thought I should close the issue that said, just wondering if you have any instructions on deployment?

**Comment by JoshBeveridge** [comment]
@theportablegeek to be totally honest, I think we might have just deployed it using a standard PHP setup on a server of ours back in the day, but for the sake of total transparency, I had some more back-end focused devs handling that side of things.

**Comment by andrewdmaclean** [comment]
@joshdrink Not to worry then - let's just close this issue - but thanks for getting back to me!
